### ISSUE TITLE
Map Language resets to local on zoom

### ISSUE THREAD

**Issue by meenalluktuke** [sghaskell/Clustered-Single-Value-Map-Visualization#4] opened 2017-04-20 08:38 UTC
Hi,

1) When I zoom in to Japan or China, the text is in local language, not English.

![image](https://cloud.githubusercontent.com/assets/18573545/25221419/588d5d3a-25b5-11e7-9096-1537b1a0ef6a.png)

2) There is no option to display text on hover? or Auto-zoom on select.

**Comment by sghaskell** [comment] 2017-04-20 16:42
Thanks for posting. I'll address your points in order.

1) The localization of the names on the map are specific to the map tile provider. Openstreetmap will attempt to render location names in the local language of the region you're viewing. The US is going to render in English, Japan in Japanese and so on. If you select any of the CartoDB tiles, they will render everything in English.

Here's an example showing the CartoDB Light tile:

<img width="716" alt="screen shot 2017-04-20 at 9 51 53 am" src="https://cloud.githubusercontent.com/assets/8450537/25242678/5384f47a-25af-11e7-99a8-fcee3ba92084.png">

2a) That's a great feature request. The default action is to click the marker to popup the dialog. I'll add a toogle to enable hover to popup the dialog.

2b) When you say auto-zoom on select, what do you mean? You want to zoom into a particular zoom level when you click on a marker from a wider zoom level?

**Comment by meenalluktuke** [comment] 2017-04-21 07:01
Hi,

Thanks for such a quick response. Appreciate a lot!

1. I tried CartoDB (light as well as dark). The map looks English until you zoom in
![image](https://cloud.githubusercontent.com/assets/18573545/25266173/823cf6ca-2670-11e7-95e5-d6481785ba53.png)



2a. I got the option for hover (field title).

2b. Yes, you got it right. Zoom in the area on selection. Auto zoom works on cluster, not individual points. 

3. Just for reference: I have customized similar kind of map as a Kibana plugin. Here is a snapshot. It is nowhere close to being awesome, but it will give you an idea.

Zoom and Hover : 
![image](https://cloud.githubusercontent.com/assets/18573545/25266288/f1c00514-2670-11e7-945f-956ea51273f8.png)

First Look: 
![image](https://cloud.githubusercontent.com/assets/18573545/25266319/0c15af2c-2671-11e7-8158-beb29b2553b7.png)

**Comment by sghaskell** [comment] 2017-04-24 16:58
1. Try this tile and attribution to see if it's any better. It attempts to put an English name beneath the localized name.

**Map Tile Override**

``https://services.arcgisonline.com/ArcGIS/rest/services/world_topo_map/MapServer/tile/{z}/{y}/{x}.png``

**Map Attribution Override**

``&copy; <a href="http://esri.com">Esri</a>``

<img width="811" alt="screen shot 2017-04-24 at 9 53 50 am" src="https://cloud.githubusercontent.com/assets/8450537/25348810/57f147b6-28d4-11e7-9653-223e9c701e36.png">

<img width="1595" alt="screen shot 2017-04-24 at 9 53 29 am" src="https://cloud.githubusercontent.com/assets/8450537/25348838/6ae45052-28d4-11e7-82c0-fcff48a81be4.png">

**Comment by sghaskell** [comment] 2017-04-24 17:05
2) You can use the **title** field to enable a hover description but it's simply plain text. I think you want to hover over the icon to display the full contents of the popup. This is easy to do, but the problem is that once you mouse off the icon, the display disappears. If you have a hyperlink or want to copy any of the text in the popup you will lose that functionality with marker hover unless you drastically tweak the icon anchor properties. I [found some code here](http://jsfiddle.net/sowelie/3JbNY/) that gets around this but I'd need to adapt it to work reliably in the Custom Visualization framework. The methods for traversing the DOM need tweaking.

I suppose it's not a big deal if you just want to quickly see a count or some other quick text in the popup. I'll add the feature with a corresponding menu setting to enable popup hover and disable click to display popup.

**Comment by sghaskell** [comment] 2017-04-24 17:20
2b. There's a ``map.flyTo()`` method that I can expose. I'll look into implementing this via a set of menu options. The sticky issue is picking the marker event to bind this to. ``Click`` is currently bound to display the popup, ``dblclick`` performs a drill-down (if enabled).  I'll test with ``mousedown`` but may ultimately need to bind to ``contextmenu`` (right click) and make 'Fly To' one of the options in the dialog box.

**Comment by meenalluktuke** [comment] 2017-05-03 09:47
Hi Scott,

First of all, thanks a lot for your quick response and help. Here is what I
have done:

1. Added title for hover and drill-down with double click.
2. Added marker color and icon
3. The map tile you sent (
https://services.arcgisonline.com/ArcGIS/rest/services/world_topo_map/MapServer/tile/{z}/{y}/{x}.png)
is better, so I am using it now.

Next step:
-> Add color legend to the map
-> Integrate with Google geocoding to search for address


Thanks,
Meenal

**Comment by sghaskell** [comment] 2017-07-10 19:21
Closing the issue since this is a localization issue with tile providers.

**Closed as completed by sghaskell** 2017-07-10 19:21 UTC
Labels: enhancement, help wanted
