### ISSUE TITLE
Fails to load source in IE 11

### ISSUE THREAD

**Issue by hettervik** [sghaskell/Clustered-Single-Value-Map-Visualization#10] opened 2017-08-08 07:27 UTC
Hi,

I've installed this application on out test environment and used it on some test data. When using Chrome, it loads the visualization just fine. When using IE 11 (11.1480.14393.0) we get error message "Failed to load source for Clustered Single Value Map Visualization visualization." I've tried started IE in private mode as well, but to no help. I've also tried having a colleague of mine do the same tests, which revealed the same results. We are running Splunk 6.5.3.

Regards,
Martin

**Comment by sghaskell** [comment] 2017-08-10 19:23
Thanks for reporting the issue, @hettervik. I'll do some testing and see if I can't find/resolve the issue. Hang tight.

Scott

**Comment by Hackencrash** [comment] 2017-09-14 10:14
Me too. IE11 (11.0.9600.18738CO) error:

> Failed to load source for Clustered Single Value Map Visualization

Works fine in FF and Chrome

**Comment by JimSimpkins13** [comment] 2017-09-18 19:01
Scott,
We are seeing this issue too with both Chrome and IE. Not all the time but frequently. No errors are being reported in the Chrome console.
-Jim

	Failed to load source for Clustered Single Value Map Visualization visualization.

**Comment by JimSimpkins13** [comment] 2017-09-18 19:05
Scott,
If I click on the open in search icon, the search gets executed and returns 86 events. But when I go to visualizations and select Clustered Single Value Map getting: Error rendering Clustered Single Value Map Visualization visualization.

Chrome console reports:
common.js:111 Uncaught TypeError: Cannot read property 'r' of null
    at child.createMarkerStyle (visualization.js:257)
    at child.updateView (visualization.js:496)
    at child.<anonymous> (common.js:111)
    at child._tryWithAsyncCatch (common.js:111)
    at child.updateView (common.js:111)
    at child._updateView (common.js:111)
    at child._updateView (common.js:111)
    at Object.validate (common.js:117)
    at Object.validate (common.js:111)
    at Object.validateAll (common.js:117)

-Jim

**Comment by JimSimpkins13** [comment] 2017-09-18 19:08
Here is sample of table we send to the map:

`

latitude | longitude | description | title | icon | markerColor
-- | -- | -- | -- | -- | --
47.6327823 | -122.3409667 | <table> <tr><td>Device:</td><td>Test iPhone 7</a></td></tr> <tr><td>User:</td><td>andys</a></td></tr> <tr><td>Received Mbsp:</td><td>12.10</a></td></tr> <tr><td>Sent Mbsp:</td><td>10.07</a></td></tr> <tr><td>Latency ms:</td><td>44.69</a></td></tr> <tr><td>Platform:</td><td>iOS</td></tr> <tr><td>Adapter:</td><td>wifi</td></tr> <tr><td>SSID:</td><td>ENG-DevNet</td></tr> <tr><td>BSSID:</td><td>88-75-56-6E-B3-0C</td></tr> <tr><td>Trigger:</td><td>scheduled</td></tr> <tr><td>Time:</td><td>Mon Sep 18 12:00:55 2017</td></tr> </table> | Test iPhone 7 | fa-apple | green
47.632772 | -122.3409642 | <table> <tr><td>Device:</td><td>Test iPhone 7</a></td></tr> <tr><td>User:</td><td>andys</a></td></tr> <tr><td>Received Mbsp:</td><td>8.16</a></td></tr> <tr><td>Sent Mbsp:</td><td>10.31</a></td></tr> <tr><td>Latency ms:</td><td>51.86</a></td></tr> <tr><td>Platform:</td><td>iOS</td></tr> <tr><td>Adapter:</td><td>wifi</td></tr> <tr><td>SSID:</td><td>ENG-DevNet</td></tr> <tr><td>BSSID:</td><td>88-75-56-6E-B3-0C</td></tr> <tr><td>Trigger:</td><td>scheduled</td></tr> <tr><td>Time:</td><td>Mon Sep 18 11:45:44 2017</td></tr> </table> | Test iPhone 7 | fa-apple | green
47.6327711 | -122.3409614 | <table> <tr><td>Device:</td><td>Test iPhone 7</a></td></tr> <tr><td>User:</td><td>andys</a></td></tr> <tr><td>Received Mbsp:</td><td>10.92</a></td></tr> <tr><td>Sent Mbsp:</td><td>11.01</a></td></tr> <tr><td>Latency ms:</td><td>39.87</a></td></tr> <tr><td>Platform:</td><td>iOS</td></tr> <tr><td>Adapter:</td><td>wifi</td></tr> <tr><td>SSID:</td><td>ENG-DevNet</td></tr> <tr><td>BSSID:</td><td>88-75-56-6E-B3-0C</td></tr> <tr><td>Trigger:</td><td>scheduled</td></tr> <tr><td>Time:</td><td>Mon Sep 18 11:30:33 2017</td></tr> </table> | Test iPhone 7 | fa-apple | green

`

**Comment by JimSimpkins13** [comment] 2017-09-18 22:27
Some more information. On the Simple XML dashboard that the map fails to load there are 10 rows with 17 panels of charts and tables all sharing a single base search. 

For a test I created another dashboard with the same base search but just the map on a single row, all the other rows/panels were deleted. 

I reloaded each dashboard 10 times. The one with just the map loaded everytime. The original one with 10 rows loaded just 4 times, 6 times it "Failed to load source for Clustered Single Value Map Visualization visualization.".

**Comment by dneal06** [comment] 2017-10-11 18:08
Hello sghaskell,

Using IE 11.0.9600.18792co and unable to load the map as well. Think maybe an IE html 5 issue. Would you be able to give a time table of when this will be fixed? Have used this for a POC for a project but unable to move forward with the project if the issue is not fixed. Awesome map otherwise.


Error - Failed to load source

**Comment by sghaskell** [comment] 2017-10-11 20:19
@dneal06 

Thanks for the feedback. The issue is with a promise in a code block that's using the ES6 standard which is not compatible with IE 11. I've fixed the code block to be ES5 compliant. I'll push a fix out shortly to Splunkbase and update the thread.

<img width="1341" alt="screen shot 2017-10-11 at 1 15 31 pm" src="https://user-images.githubusercontent.com/8450537/31464501-a3bd1e76-ae86-11e7-8292-c0f0500c3d16.png">

**Comment by sghaskell** [comment] 2017-10-11 21:29
I've uploaded version 1.5.8 to Splunkbase with the fix.

**Closed as completed by sghaskell** 2017-10-11 21:29 UTC
Labels: bug
